spring.application.name=evaluacion
server.port=8080
# Clave secreta para la firma JWT (mínimo 256 bits / 32 caracteres)
jwt.secret=ClaveSecretaParaLaPruebaTecnicaEconocom
# Tiempo de expiración del token (1 hora en milisegundos)
jwt.expiration-ms=3600000